spring:
  application:
    name: video-service
  mvc:
    servlet:
      path: /api
  datasource:
    url: jdbc:postgresql://localhost:5433/video_streaming_api_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
    listener:
      ack-mode: manual
      concurrency: 3
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/