spring:
  application:
    name: migration-service
  datasource:
    url: jdbc:postgresql://localhost:5433/video_streaming_api_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/