spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: video_service
          uri: lb://video-service
          predicates:
            - Path=/api/video/**
        - id: video_metadata_service
          uri: lb://video-metadata-service
          predicates:
            - Path=/api/video/metadata/**
        - id: video_statistic_service
          uri: lb://video-statistic-service
          predicates:
            - Path=/api/video/statistic/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/